// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc28e_e7hdpiWa8_srivhj9r487A9CyFU',
    appId: '1:468037307240:web:a1e38fbde25197e348e4dd',
    messagingSenderId: '468037307240',
    projectId: 'eshop-ae14c',
    authDomain: 'eshop-ae14c.firebaseapp.com',
    databaseURL: 'https://eshop-ae14c-default-rtdb.firebaseio.com',
    storageBucket: 'eshop-ae14c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9A2bThJ6ry5_AlrUF5sXuMX3fRPSRwWs',
    appId: '1:468037307240:android:8cfcf01c07741eae48e4dd',
    messagingSenderId: '468037307240',
    projectId: 'eshop-ae14c',
    databaseURL: 'https://eshop-ae14c-default-rtdb.firebaseio.com',
    storageBucket: 'eshop-ae14c.firebasestorage.app',
  );
}
